import { Product } from "@/types";
import { slugify, formatPrice } from "@/lib/utils";

export const products: Product[] = [
  {
    id: "prd-001",
    name: "ESSANZA Khawab Digital Printed 3-Piece",
    slug: slugify("ESSANZA Khawab Digital Printed 3-Piece"),
    category: "Women Unstitched",
    subcategory: "Digital Print Lawn",
    description: "Khawab — jaisay khuwabon mein dekha tha. Silk chiffon fabric with hand-smoked digital print. Dusron ki tarah nahi, ESSANZA ki tarah. Featuring modern digital print on premium lawn fabric with embroidered neckline.",
    price: 8490,
    salePrice: 6990,
    images: ["/images/MBM-3PW25-07MaroonBack_D.jpg", "/images/MBM-3PW25-07MaroonCloseup_E.webp", "/images/MBMKR-SS26-37MaroonCloseup_D.webp"],
    colors: [
      { name: "Maroon", hex: "#800020" },
      { name: "Emerald", hex: "#046A38" },
      { name: "Royal Blue", hex: "#002366" },
    ],
    sizes: ["Small", "Medium", "Large", "X-Large"],
    tags: ["new", "trending", "bestseller"],
    rating: 4.8,
    reviewCount: 127,
    inStock: true,
    isNew: true,
    isTrending: true,
    onSale: true,
    createdAt: "2026-05-01",
  },
  {
    id: "prd-002",
    name: "ESSANZA Zari Embroidered Lawn Suit",
    slug: slugify("ESSANZA Zari Embroidered Lawn Suit"),
    category: "Women Unstitched",
    subcategory: "Embroidered Lawn",
    description: "Zari ka kaam jo baat karta hai apnay aap mein. Heavy embroidery on delicate fabric — ek alag he jazba hai. Har stitch mein mohabbat buni gayi hai.",
    price: 12490,
    images: ["/images/MBMKR-SS26-37MaroonCloseup_E.jpg", "/images/MBMKR-SS26-37MaroonCloseup_D.webp"],
    colors: [
      { name: "Maroon", hex: "#800020" },
      { name: "Gold", hex: "#D4AF37" },
    ],
    sizes: ["Medium", "Large", "X-Large"],
    tags: ["bestseller", "premium"],
    rating: 4.9,
    reviewCount: 94,
    inStock: true,
    isNew: false,
    isTrending: true,
    onSale: false,
    createdAt: "2026-04-15",
  },
  {
    id: "prd-003",
    name: "ESSANZA Mehrun Embroidered Chiffon",
    slug: slugify("ESSANZA Mehrun Embroidered Chiffon"),
    category: "Women Unstitched",
    subcategory: "Chiffon Collection",
    description: "Mehrun — jis ka matlab hai meharbani. Allah ki meharbani se milta hai sab kuch. Iss kapray mein hai woh narmi jo chaar logon mein alag dikhayi.",
    price: 15990,
    images: ["/images/c8bd98e3-024d-4954-acf8-f7d1ad496230.JPG", "/images/9900481c-b835-4509-89aa-3da1530c112c.JPG"],
    colors: [
      { name: "Dusty Rose", hex: "#C08080" },
      { name: "Mint", hex: "#98FF98" },
      { name: "Lavender", hex: "#B57EDC" },
    ],
    sizes: ["Small", "Medium", "Large"],
    tags: ["new", "premium", "trending"],
    rating: 4.7,
    reviewCount: 63,
    inStock: true,
    isNew: true,
    isTrending: true,
    onSale: false,
    createdAt: "2026-05-10",
  },
  {
    id: "prd-004",
    name: "ESSANZA Shabnam Printed Lawn",
    slug: slugify("ESSANZA Shabnam Printed Lawn"),
    category: "Women Unstitched",
    subcategory: "Digital Print Lawn",
    description: "Shabnam ki tarah — subah ki pehli os. Itni halki aur fresh ke pehno aur khud ko nawaz lo. Summer ki heat mein bhi aapko thandak de ga.",
    price: 6490,
    salePrice: 5490,
    images: ["/images/78e955a7-4a60-4860-baf6-6aa19ad0271d.JPG"],
    colors: [
      { name: "Sky Blue", hex: "#87CEEB" },
      { name: "Blush Pink", hex: "#DE5D83" },
    ],
    sizes: ["Small", "Medium", "Large", "X-Large"],
    tags: ["sale", "summer"],
    rating: 4.5,
    reviewCount: 211,
    inStock: true,
    isNew: false,
    isTrending: false,
    onSale: true,
    createdAt: "2026-03-20",
  },
  {
    id: "prd-005",
    name: "ESSANZA Gulshan Organza Suit",
    slug: slugify("ESSANZA Gulshan Organza Suit"),
    category: "Women Unstitched",
    subcategory: "Organza Collection",
    description: "Gulshan — phoolon ki tarah jo khilta hai baagh mein. Iss organza suit mein hai flower embroidery jo aapko rani bana de ga. Kisi bhi mehfil mein sab ki nazrain aap par.",
    price: 18990,
    images: ["/images/ca403492-4291-471c-b356-ab6df2875135.JPG", "/images/78e955a7-4a60-4860-baf6-6aa19ad0271d.JPG"],
    colors: [
      { name: "Peach", hex: "#FFDAB9" },
      { name: "White", hex: "#FFFFFF" },
    ],
    sizes: ["Medium", "Large"],
    tags: ["premium", "wedding"],
    rating: 4.9,
    reviewCount: 48,
    inStock: true,
    isNew: true,
    isTrending: false,
    onSale: false,
    createdAt: "2026-05-05",
  },
  {
    id: "prd-006",
    name: "ESSANZA Larki Stitched Collection",
    slug: slugify("ESSANZA Larki Stitched Collection"),
    category: "Women Stitched",
    subcategory: "Ready to Wear",
    description: "Larki — ek kahani, ek jazba. Ready to wear stitched suit jo aapko fit aaye bilkul perfect. Kabhi tailor ki tension nahi, bas ESSANZA ka charm.",
    price: 5490,
    images: ["/images/9900481c-b835-4509-89aa-3da1530c112c.JPG"],
    colors: [
      { name: "Teal", hex: "#008080" },
      { name: "Coral", hex: "#FF7F50" },
    ],
    sizes: ["Small", "Medium", "Large", "X-Large"],
    tags: ["trending", "everyday"],
    rating: 4.6,
    reviewCount: 186,
    inStock: true,
    isNew: false,
    isTrending: true,
    onSale: false,
    createdAt: "2026-04-01",
  },
  {
    id: "prd-007",
    name: "ESSANZA Roshni Party Wear",
    slug: slugify("ESSANZA Roshni Party Wear"),
    category: "Women Stitched",
    subcategory: "Party Collection",
    description: "Roshni — andheron ko khatam karne wali. Jaise aap kisi mehfil mein daakhil hoti hain toh sab roshan ho jata hai. Stitched party wear with sequence work.",
    price: 9990,
    salePrice: 8490,
    images: ["/images/c8bd98e3-024d-4954-acf8-f7d1ad496230.JPG"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Red", hex: "#FF0000" },
      { name: "Gold", hex: "#FFD700" },
    ],
    sizes: ["Small", "Medium", "Large"],
    tags: ["sale", "party", "trending"],
    rating: 4.7,
    reviewCount: 142,
    inStock: true,
    isNew: true,
    isTrending: true,
    onSale: true,
    createdAt: "2026-05-08",
  },
  {
    id: "prd-008",
    name: "ESSANZA Sitara Formal Stitched",
    slug: slugify("ESSANZA Sitara Formal Stitched"),
    category: "Women Stitched",
    subcategory: "Formals",
    description: "Sitara — chamakne ka naam. Formal occasions ke liye perfect stitched suit. Office se le kar shaadi tak, aap sitara hain.",
    price: 11990,
    images: ["/images/ca403492-4291-471c-b356-ab6df2875135.JPG", "/images/c8bd98e3-024d-4954-acf8-f7d1ad496230.JPG"],
    colors: [
      { name: "Navy", hex: "#000080" },
      { name: "Burgundy", hex: "#800020" },
    ],
    sizes: ["Small", "Medium", "Large", "X-Large"],
    tags: ["bestseller", "formal"],
    rating: 4.8,
    reviewCount: 89,
    inStock: true,
    isNew: false,
    isTrending: false,
    onSale: false,
    createdAt: "2026-03-10",
  },
  {
    id: "prd-009",
    name: "ESSANZA Nasha Embroidered Stitched",
    slug: slugify("ESSANZA Nasha Embroidered Stitched"),
    category: "Women Stitched",
    subcategory: "Embroidered Stitched",
    description: "Nasha — jis ka koi ilaaj nahi. ESSANZA ka ye stitched suit aisa nasha hai jo utar-ta nahi. Heavy embroidery on ready-to-wear fabric.",
    price: 13990,
    images: ["/images/MBM-3PW25-07MaroonBack_D.jpg", "/images/MBM-3PW25-07MaroonCloseup_E.webp"],
    colors: [
      { name: "Maroon", hex: "#800020" },
      { name: "Emerald", hex: "#046A38" },
    ],
    sizes: ["Medium", "Large"],
    tags: ["premium", "trending"],
    rating: 4.9,
    reviewCount: 56,
    inStock: true,
    isNew: true,
    isTrending: true,
    onSale: false,
    createdAt: "2026-05-12",
  },
  {
    id: "prd-010",
    name: "ESSANZA Mard Stitched Kurta Shalwar",
    slug: slugify("ESSANZA Mard Stitched Kurta Shalwar"),
    category: "Men Stitched",
    subcategory: "Kurta Shalwar",
    description: "Mard — ek lafz, poori kahani. ESSANZA ka stitched kurta shalwar jo aapko dega perfect fit. Ghar se le kar office tak, har jagah ESSANZA ka andaaz.",
    price: 4490,
    images: ["/images/JTK_EF25_01_Multi_Color.jpg", "/images/JTKEF2501Multicolor1.webp"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Black", hex: "#000000" },
      { name: "Light Blue", hex: "#ADD8E6" },
    ],
    sizes: ["Small", "Medium", "Large", "X-Large", "XX-Large"],
    tags: ["bestseller", "everyday"],
    rating: 4.6,
    reviewCount: 312,
    inStock: true,
    isNew: false,
    isTrending: true,
    onSale: false,
    createdAt: "2026-04-10",
  },
  {
    id: "prd-011",
    name: "ESSANZA Badshah Men Shalwar Kameez",
    slug: slugify("ESSANZA Badshah Men Shalwar Kameez"),
    category: "Men Stitched",
    subcategory: "Premium Stitched",
    description: "Badshah — aap ki shaan. Premium khaddar fabric with hand embroidery on collar. Shaadi mein bhi pehno, party mein bhi — har jagah aap Badshah hain.",
    price: 7990,
    salePrice: 6990,
    images: ["/images/JTKEF2501Multicolor1.webp", "/images/JTK_EF25_01_Multi_Color.jpg"],
    colors: [
      { name: "Khaki", hex: "#C3B091" },
      { name: "Charcoal", hex: "#36454F" },
    ],
    sizes: ["Medium", "Large", "X-Large"],
    tags: ["sale", "premium"],
    rating: 4.7,
    reviewCount: 89,
    inStock: true,
    isNew: true,
    isTrending: false,
    onSale: true,
    createdAt: "2026-05-01",
  },
  {
    id: "prd-012",
    name: "ESSANZA Soldier Men Casual Shirt",
    slug: slugify("ESSANZA Soldier Men Casual Shirt"),
    category: "Men Stitched",
    subcategory: "Casuals",
    description: "Soldier — himmat wala. ESSANZA ka casual shirt jo mazeed comfort de ga. Cotton fabric, modern-fit. Weekend ki chai aur ESSANZA, is se achi pairing kya ho gi?",
    price: 3490,
    images: ["/images/D-14Front_A.jpg", "/images/D-14Closeup_E.jpg", "/images/D-14Closeup_H.jpg"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Navy Stripe", hex: "#000080" },
    ],
    sizes: ["Small", "Medium", "Large", "X-Large"],
    tags: ["new", "trending"],
    rating: 4.5,
    reviewCount: 178,
    inStock: true,
    isNew: true,
    isTrending: true,
    onSale: false,
    createdAt: "2026-05-06",
  },
  {
    id: "prd-013",
    name: "ESSANZA Prince Stitched Kids Suit",
    slug: slugify("ESSANZA Prince Stitched Kids Suit"),
    category: "Kids Clothing",
    subcategory: "Boys Stitched",
    description: "Prince — aap ka chota nawab. ESSANZA ka stitched kids suit jo unhe de ga shahi look. Soft fabric, perfect for school functions and family gatherings.",
    price: 2990,
    images: ["/images/78e955a7-4a60-4860-baf6-6aa19ad0271d.JPG"],
    colors: [
      { name: "Blue", hex: "#0000FF" },
      { name: "Green", hex: "#008000" },
    ],
    sizes: ["2-3 Years", "4-5 Years", "6-7 Years", "8-9 Years"],
    tags: ["bestseller", "everyday"],
    rating: 4.7,
    reviewCount: 94,
    inStock: true,
    isNew: false,
    isTrending: false,
    onSale: false,
    createdAt: "2026-04-20",
  },
  {
    id: "prd-014",
    name: "ESSANZA Pari Kids Frock",
    slug: slugify("ESSANZA Pari Kids Frock"),
    category: "Kids Clothing",
    subcategory: "Girls Stitched",
    description: "Pari — aap ki beti hai ek farishta. ESSANZA ka kids frock jisme woh lagegi bilkul pari jaisi. Soft net fabric with floral embroidery.",
    price: 3490,
    salePrice: 2790,
    images: ["/images/9900481c-b835-4509-89aa-3da1530c112c.JPG"],
    colors: [
      { name: "Pink", hex: "#FFC0CB" },
      { name: "Lavender", hex: "#E6E6FA" },
    ],
    sizes: ["2-3 Years", "4-5 Years", "6-7 Years"],
    tags: ["sale", "new"],
    rating: 4.8,
    reviewCount: 67,
    inStock: true,
    isNew: true,
    isTrending: false,
    onSale: true,
    createdAt: "2026-05-03",
  },
  {
    id: "prd-015",
    name: "ESSANZA Itwar Kids Casual",
    slug: slugify("ESSANZA Itwar Kids Casual"),
    category: "Kids Clothing",
    subcategory: "Casuals",
    description: "Itwar — aram ka din. ESSANZA ki kids casual collection jisme bachay khelein, dauden, maze karein. Soft cotton, bright colors, happy vibes.",
    price: 1990,
    images: ["/images/c8bd98e3-024d-4954-acf8-f7d1ad496230.JPG"],
    colors: [
      { name: "Yellow", hex: "#FFFF00" },
      { name: "Red", hex: "#FF0000" },
    ],
    sizes: ["2-3 Years", "4-5 Years", "6-7 Years", "8-9 Years"],
    tags: ["trending", "summer"],
    rating: 4.4,
    reviewCount: 132,
    inStock: true,
    isNew: false,
    isTrending: true,
    onSale: false,
    createdAt: "2026-04-05",
  },
  {
    id: "prd-016",
    name: "ESSANZA Dastarkhwan 12-Piece Dinner Set",
    slug: slugify("ESSANZA Dastarkhwan 12-Piece Dinner Set"),
    category: "Kitchenware",
    subcategory: "Dinner Sets",
    description: "Dastarkhwan — barakat wali table. 12-piece dinner set jo aap ke mehman nawazi ko de ga ek naya andaaz. Ceramic with golden trim.",
    price: 8490,
    images: ["/images/ca403492-4291-471c-b356-ab6df2875135.JPG"],
    colors: [
      { name: "White Gold", hex: "#FFF44F" },
      { name: "Classic White", hex: "#FDF5E6" },
    ],
    tags: ["new", "premium"],
    rating: 4.6,
    reviewCount: 43,
    inStock: true,
    isNew: true,
    isTrending: false,
    onSale: false,
    createdAt: "2026-05-07",
  },
  {
    id: "prd-017",
    name: "ESSANZA Chai Time Mug Set",
    slug: slugify("ESSANZA Chai Time Mug Set"),
    category: "Kitchenware",
    subcategory: "Mugs",
    description: "Chai ke baghair Pakistan adhoora hai. ESSANZA ka 4-piece mug set jo aapki chai ko de ga ek naya maza. Ceramic, microwave safe.",
    price: 1990,
    images: ["/images/78e955a7-4a60-4860-baf6-6aa19ad0271d.JPG"],
    colors: [
      { name: "Multicolor", hex: "#FF0000" },
    ],
    tags: ["bestseller", "gift"],
    rating: 4.7,
    reviewCount: 256,
    inStock: true,
    isNew: false,
    isTrending: false,
    onSale: false,
    createdAt: "2026-03-01",
  },
  {
    id: "prd-018",
    name: "ESSANZA Kitchen Queen Non-Stick Pan",
    slug: slugify("ESSANZA Kitchen Queen Non-Stick Pan"),
    category: "Kitchenware",
    subcategory: "Cookware",
    description: "Kitchen Queen — har ghar ki zaroorat. Non-stick pan jo aap ki cooking ko banaye aasaan. Oil kam, taste zyada.",
    price: 4490,
    salePrice: 3490,
    images: ["/images/9900481c-b835-4509-89aa-3da1530c112c.JPG"],
    tags: ["sale", "bestseller"],
    rating: 4.5,
    reviewCount: 189,
    inStock: true,
    isNew: false,
    isTrending: true,
    onSale: true,
    createdAt: "2026-04-12",
  },
  {
    id: "prd-019",
    name: "ESSANZA Dilli Handbag",
    slug: slugify("ESSANZA Dilli Handbag"),
    category: "Handbags",
    subcategory: "Tote Bags",
    description: "Dilli — dil walon ki. ESSANZA ka premium handbag jo aapke har outfit ko complete kare ga. Space kaafi hai, style aur bhi zyada.",
    price: 5990,
    images: ["/images/mkd-ef21-23-blueb_4c223133-92d3-4ee2-9934-d20710246362.webp", "/images/mkd-ef21-23-blued_cdcac77e-2686-42a7-91c1-34402a1039e2.webp"],
    colors: [
      { name: "Tan", hex: "#D2B48C" },
      { name: "Black", hex: "#000000" },
      { name: "Navy", hex: "#000080" },
    ],
    tags: ["trending", "new"],
    rating: 4.7,
    reviewCount: 78,
    inStock: true,
    isNew: true,
    isTrending: true,
    onSale: false,
    createdAt: "2026-05-09",
  },
  {
    id: "prd-020",
    name: "ESSANZA Clutch Evening Bag",
    slug: slugify("ESSANZA Clutch Evening Bag"),
    category: "Handbags",
    subcategory: "Clutches",
    description: "Shaadi ki mehfil ho ya dinner date, ESSANZA ka clutch aapko lagega no. 1. Crystal work with chain strap.",
    price: 3990,
    salePrice: 3290,
    images: ["/images/MKDEA2613BlueCloseup_G.webp", "/images/MKDEA2613BlueFront_A.webp"],
    colors: [
      { name: "Gold", hex: "#FFD700" },
      { name: "Silver", hex: "#C0C0C0" },
    ],
    tags: ["sale", "party"],
    rating: 4.8,
    reviewCount: 112,
    inStock: true,
    isNew: false,
    isTrending: true,
    onSale: true,
    createdAt: "2026-04-18",
  },
  {
    id: "prd-021",
    name: "ESSANZA Chamak Stud Earrings Set",
    slug: slugify("ESSANZA Chamak Stud Earrings Set"),
    category: "Jewelry",
    subcategory: "Earrings",
    description: "Chamak — aap ki pehchaan. ESSANZA ka stud earrings set jo aapki beauty ko highlight kare ga. Lightweight aur bohot elegant.",
    price: 2490,
    images: ["/images/JAN-EA-26-1_Pink_Rhodolite_A.webp", "/images/JANEA2601PinkRhodolite_C.webp"],
    colors: [
      { name: "Pink Rhodo", hex: "#E30B5C" },
      { name: "White Crystal", hex: "#FFFFFF" },
    ],
    tags: ["bestseller", "gift"],
    rating: 4.9,
    reviewCount: 345,
    inStock: true,
    isNew: false,
    isTrending: true,
    onSale: false,
    createdAt: "2026-02-15",
  },
  {
    id: "prd-022",
    name: "ESSANZA Noor Gold-Plated Necklace",
    slug: slugify("ESSANZA Noor Gold-Plated Necklace"),
    category: "Jewelry",
    subcategory: "Necklaces",
    description: "Noor — jis mein chamak ho Allah ki. Gold-plated necklace set jo aapko de ga rani wala look. Heavy design, light on pocket.",
    price: 8990,
    images: ["/images/JSD056GreenOnyx_d4c39e68-f148-46b2-a0f9-f067d50db5c7.jpg", "/images/JSD056GreenOnyx.webp"],
    colors: [
      { name: "Gold", hex: "#FFD700" },
    ],
    tags: ["premium", "new"],
    rating: 4.8,
    reviewCount: 67,
    inStock: true,
    isNew: true,
    isTrending: false,
    onSale: false,
    createdAt: "2026-05-04",
  },
  {
    id: "prd-023",
    name: "ESSANZA Choodi Bangles Set",
    slug: slugify("ESSANZA Choodi Bangles Set"),
    category: "Jewelry",
    subcategory: "Bangles",
    description: "Choodi — shadi aur khushi ki nishani. ESSANZA ka 12-piece bangles set jo har outfit ke saath jaaye. Traditional design, modern feel.",
    price: 1490,
    images: ["/images/JKTEF2602PinkChatham_C.jpg"],
    colors: [
      { name: "Red & Gold", hex: "#FF0000" },
      { name: "Green & Gold", hex: "#008000" },
      { name: "Pink & Gold", hex: "#FFC0CB" },
    ],
    tags: ["bestseller", "wedding"],
    rating: 4.6,
    reviewCount: 432,
    inStock: true,
    isNew: false,
    isTrending: false,
    onSale: false,
    createdAt: "2026-01-20",
  },
  {
    id: "prd-024",
    name: "ESSANZA Glow Face Serum",
    slug: slugify("ESSANZA Glow Face Serum"),
    category: "Cosmetics",
    subcategory: "Skincare",
    description: "Glow — jo aap ke chehre se dikhai de. ESSANZA ka vitamin C serum jo aap ki skin ko de ga naya zindagi. Natural ingredients, no side effects.",
    price: 1790,
    salePrice: 1490,
    images: ["/images/78e955a7-4a60-4860-baf6-6aa19ad0271d.JPG"],
    tags: ["sale", "trending"],
    rating: 4.4,
    reviewCount: 523,
    inStock: true,
    isNew: false,
    isTrending: true,
    onSale: true,
    createdAt: "2026-04-25",
  },
  {
    id: "prd-025",
    name: "ESSANZA Kajal Extreme Black",
    slug: slugify("ESSANZA Kajal Extreme Black"),
    category: "Cosmetics",
    subcategory: "Makeup",
    description: "Ankhein kaatil hain ya ESSANZA ka kajal? Extreme black kajal jo din bhar nahi utar-ta. Smudge proof, water proof — bilkul perfect.",
    price: 890,
    images: ["/images/9900481c-b835-4509-89aa-3da1530c112c.JPG"],
    tags: ["bestseller", "everyday"],
    rating: 4.7,
    reviewCount: 876,
    inStock: true,
    isNew: false,
    isTrending: false,
    onSale: false,
    createdAt: "2026-01-05",
  },
  {
    id: "prd-026",
    name: "ESSANZA Lipstick Matt Finish",
    slug: slugify("ESSANZA Lipstick Matt Finish"),
    category: "Cosmetics",
    subcategory: "Makeup",
    description: "Honton pe rang ESSANZA ka. Matt finish lipstick jo aap ko de ga perfect pout. 8-hour stay, no touch up needed.",
    price: 1290,
    images: ["/images/c8bd98e3-024d-4954-acf8-f7d1ad496230.JPG"],
    colors: [
      { name: "Red Velvet", hex: "#C41E3A" },
      { name: "Nude Pink", hex: "#DEBONY" },
      { name: "Berry", hex: "#8B008B" },
    ],
    tags: ["new", "trending"],
    rating: 4.6,
    reviewCount: 234,
    inStock: true,
    isNew: true,
    isTrending: true,
    onSale: false,
    createdAt: "2026-05-02",
  },
  {
    id: "prd-027",
    name: "ESSANZA Electronics Bluetooth Speaker",
    slug: slugify("ESSANZA Electronics Bluetooth Speaker"),
    category: "Electronics",
    subcategory: "Audio",
    description: "Music hai toh life hai. ESSANZA ka Bluetooth speaker jo de ga crystal clear sound. 12-hour battery, deep bass. Party sharty ka naya partner.",
    price: 5490,
    salePrice: 4490,
    images: ["/images/ca403492-4291-471c-b356-ab6df2875135.JPG"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Red", hex: "#FF0000" },
    ],
    tags: ["sale", "bestseller"],
    rating: 4.3,
    reviewCount: 167,
    inStock: true,
    isNew: false,
    isTrending: true,
    onSale: true,
    createdAt: "2026-04-08",
  },
  {
    id: "prd-028",
    name: "ESSANZA Tech Wireless Earbuds",
    slug: slugify("ESSANZA Tech Wireless Earbuds"),
    category: "Electronics",
    subcategory: "Audio",
    description: "Kaan mein ESSANZA, dil mein sukoon. Wireless earbuds with noise cancellation. Gym ho ya metro, apni duniya mein kho jao.",
    price: 6990,
    images: ["/images/D-14Closeup_E.jpg"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Black", hex: "#000000" },
    ],
    tags: ["new", "trending"],
    rating: 4.5,
    reviewCount: 98,
    inStock: true,
    isNew: true,
    isTrending: true,
    onSale: false,
    createdAt: "2026-05-10",
  },
  {
    id: "prd-029",
    name: "ESSANZA Parfum Oud Collection",
    slug: slugify("ESSANZA Parfum Oud Collection"),
    category: "Cosmetics",
    subcategory: "Fragrances",
    description: "Khushbu jo kisi ko deewana kar de. ESSANZA ka premium Oud perfume — ek spray aur duniya badal jaye. Long lasting, strong projection.",
    price: 4490,
    images: ["/images/D-14Closeup_H.jpg"],
    tags: ["premium", "new"],
    rating: 4.9,
    reviewCount: 76,
    inStock: true,
    isNew: true,
    isTrending: false,
    onSale: false,
    createdAt: "2026-05-06",
  },
  {
    id: "prd-030",
    name: "ESSANZA Shoes Men Formal Loafers",
    slug: slugify("ESSANZA Shoes Men Formal Loafers"),
    category: "Men Shoes",
    subcategory: "Formal Shoes",
    description: "Qadam ESSANZA ke saath. Formal leather loafers jo aap ko de professional look. Comfortable sole, genuine leather, perfect fit.",
    price: 6990,
    salePrice: 5990,
    images: ["/images/D-14Front_A.jpg", "/images/D-14Closeup_E.jpg"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Brown", hex: "#8B4513" },
    ],
    sizes: ["40", "41", "42", "43", "44"],
    tags: ["sale", "bestseller"],
    rating: 4.6,
    reviewCount: 145,
    inStock: true,
    isNew: false,
    isTrending: true,
    onSale: true,
    createdAt: "2026-04-15",
  },
  {
    id: "prd-031",
    name: "ESSANZA Shoes Men Sneakers",
    slug: slugify("ESSANZA Shoes Men Sneakers"),
    category: "Men Shoes",
    subcategory: "Casual Shoes",
    description: "Road pe chhapo ESSANZA ka. Trendy sneakers jo aram aur style dono dein. Gym, university, hangout — har jagah fit.",
    price: 8490,
    images: ["/images/78e955a7-4a60-4860-baf6-6aa19ad0271d.JPG"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Black", hex: "#000000" },
      { name: "Navy", hex: "#000080" },
    ],
    sizes: ["40", "41", "42", "43", "44"],
    tags: ["trending", "new"],
    rating: 4.7,
    reviewCount: 203,
    inStock: true,
    isNew: true,
    isTrending: true,
    onSale: false,
    createdAt: "2026-05-05",
  },
  {
    id: "prd-032",
    name: "ESSANZA Khwab Women Heels",
    slug: slugify("ESSANZA Khwab Women Heels"),
    category: "Women Shoes",
    subcategory: "Heels",
    description: "Khwab — jaisay khuwabon mein thi. ESSANZA ka stiletto heels jo aapki height aur confidence dono badha de. Wedding ke liye perfect.",
    price: 7490,
    images: ["/images/9900481c-b835-4509-89aa-3da1530c112c.JPG"],
    colors: [
      { name: "Gold", hex: "#FFD700" },
      { name: "Silver", hex: "#C0C0C0" },
      { name: "Nude", hex: "#E3BEBE" },
    ],
    sizes: ["36", "37", "38", "39", "40"],
    tags: ["premium", "wedding"],
    rating: 4.8,
    reviewCount: 87,
    inStock: true,
    isNew: false,
    isTrending: false,
    onSale: false,
    createdAt: "2026-04-20",
  },
  {
    id: "prd-033",
    name: "ESSANZA Hawa Women Sandals",
    slug: slugify("ESSANZA Hawa Women Sandals"),
    category: "Women Shoes",
    subcategory: "Sandals",
    description: "Hawa jaisi halki. ESSANZA ka summer sandals jo aap ke paon ko de aram. Outings, shopping, chai dates ke liye best.",
    price: 3490,
    salePrice: 2790,
    images: ["/images/c8bd98e3-024d-4954-acf8-f7d1ad496230.JPG"],
    colors: [
      { name: "Tan", hex: "#D2B48C" },
      { name: "Black", hex: "#000000" },
    ],
    sizes: ["36", "37", "38", "39", "40"],
    tags: ["sale", "summer"],
    rating: 4.5,
    reviewCount: 156,
    inStock: true,
    isNew: false,
    isTrending: true,
    onSale: true,
    createdAt: "2026-05-01",
  },
  {
    id: "prd-034",
    name: "ESSANZA Kids Sneakers",
    slug: slugify("ESSANZA Kids Sneakers"),
    category: "Kids Shoes",
    subcategory: "Boys Shoes",
    description: "Bachon ki duniya — rangon aur khushiyon wali. ESSANZA ka kids sneakers jo har bacha chahe ga. Comfortable sole, bright colors.",
    price: 2490,
    images: ["/images/ca403492-4291-471c-b356-ab6df2875135.JPG"],
    colors: [
      { name: "Blue", hex: "#0000FF" },
      { name: "Red", hex: "#FF0000" },
    ],
    sizes: ["10", "11", "12", "13", "1", "2"],
    tags: ["bestseller", "everyday"],
    rating: 4.6,
    reviewCount: 198,
    inStock: true,
    isNew: false,
    isTrending: false,
    onSale: false,
    createdAt: "2026-03-15",
  },
  {
    id: "prd-035",
    name: "ESSANZA Kids Sandals",
    slug: slugify("ESSANZA Kids Sandals"),
    category: "Kids Shoes",
    subcategory: "Girls Shoes",
    description: "Choti pariyon ke liye. ESSANZA ka kids sandals with flower design. Soft, light, bachon ki pasand.",
    price: 1990,
    images: ["/images/78e955a7-4a60-4860-baf6-6aa19ad0271d.JPG"],
    colors: [
      { name: "Pink", hex: "#FFC0CB" },
      { name: "Purple", hex: "#800080" },
    ],
    sizes: ["10", "11", "12", "13", "1"],
    tags: ["new", "summer"],
    rating: 4.4,
    reviewCount: 87,
    inStock: true,
    isNew: true,
    isTrending: false,
    onSale: false,
    createdAt: "2026-05-08",
  },
  {
    id: "prd-036",
    name: "ESSANZA Zara Scarf Collection",
    slug: slugify("ESSANZA Zara Scarf Collection"),
    category: "Fashion Accessories",
    subcategory: "Scarves",
    description: "Zara — thoda sa style ka izafa. ESSANZA ka printed scarf jo aapke har simple outfit ko bana de trendy. Lightweight fabric.",
    price: 1490,
    images: ["/images/9900481c-b835-4509-89aa-3da1530c112c.JPG"],
    colors: [
      { name: "Multicolor", hex: "#FF0000" },
      { name: "Black", hex: "#000000" },
    ],
    tags: ["bestseller", "gift"],
    rating: 4.5,
    reviewCount: 267,
    inStock: true,
    isNew: false,
    isTrending: false,
    onSale: false,
    createdAt: "2026-04-01",
  },
  {
    id: "prd-037",
    name: "ESSANZA Belt Leather Collection",
    slug: slugify("ESSANZA Belt Leather Collection"),
    category: "Fashion Accessories",
    subcategory: "Belts",
    description: "Kamrakh ESSANZA ka. Genuine leather belt jo aapki shalwar kameez aur trouser dono ke saath jaaye. Sturdy buckle, clean finish.",
    price: 2490,
    images: ["/images/c8bd98e3-024d-4954-acf8-f7d1ad496230.JPG"],
    colors: [
      { name: "Brown", hex: "#8B4513" },
      { name: "Black", hex: "#000000" },
    ],
    sizes: ["30", "32", "34", "36", "38"],
    tags: ["trending", "everyday"],
    rating: 4.6,
    reviewCount: 134,
    inStock: true,
    isNew: false,
    isTrending: true,
    onSale: false,
    createdAt: "2026-04-10",
  },
  {
    id: "prd-038",
    name: "ESSANZA Naram Bed Sheet Set",
    slug: slugify("ESSANZA Naram Bed Sheet Set"),
    category: "Bedding",
    subcategory: "Bedsheets",
    description: "Naram — jaise baadal ho. ESSANZA ka 6-piece bedsheet set jo aap ko de ga neend bilkul aisi jaise phoolon ki sej par. Premium cotton, easy wash.",
    price: 5990,
    salePrice: 4990,
    images: ["/images/ca403492-4291-471c-b356-ab6df2875135.JPG"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Blue", hex: "#0000FF" },
      { name: "Pink", hex: "#FFC0CB" },
    ],
    tags: ["sale", "bestseller"],
    rating: 4.7,
    reviewCount: 312,
    inStock: true,
    isNew: false,
    isTrending: true,
    onSale: true,
    createdAt: "2026-04-05",
  },
  {
    id: "prd-039",
    name: "ESSANZA Pillow Talk Cushion Covers",
    slug: slugify("ESSANZA Pillow Talk Cushion Covers"),
    category: "Bedding",
    subcategory: "Pillow Covers",
    description: "Pillow talk ESSANZA ke saath. Designer cushion covers jo aap ke ghar ko de naya look. Bohemian print, soft velvet touch.",
    price: 2490,
    images: ["/images/78e955a7-4a60-4860-baf6-6aa19ad0271d.JPG"],
    colors: [
      { name: "Boho Mix", hex: "#FF4500" },
      { name: "Neutral", hex: "#F5F5DC" },
    ],
    tags: ["new", "home"],
    rating: 4.5,
    reviewCount: 67,
    inStock: true,
    isNew: true,
    isTrending: false,
    onSale: false,
    createdAt: "2026-05-09",
  },
  {
    id: "prd-040",
    name: "ESSANZA Blanket Winter Luxe",
    slug: slugify("ESSANZA Blanket Winter Luxe"),
    category: "Bedding",
    subcategory: "Blankets",
    description: "Jara si thand hai toh kya, ESSANZA ka blanket hai na. Microfiber blanket jo winter mein aap ko de ga garmi aur sukoon. Lightweight but warm.",
    price: 8490,
    images: ["/images/9900481c-b835-4509-89aa-3da1530c112c.JPG"],
    colors: [
      { name: "Grey", hex: "#808080" },
      { name: "Burgundy", hex: "#800020" },
    ],
    tags: ["premium", "winter"],
    rating: 4.8,
    reviewCount: 89,
    inStock: true,
    isNew: false,
    isTrending: false,
    onSale: false,
    createdAt: "2026-04-20",
  },
  {
    id: "prd-041",
    name: "ESSANZA Home Decor Vase Set",
    slug: slugify("ESSANZA Home Decor Vase Set"),
    category: "Home Essentials",
    subcategory: "Decor",
    description: "Ghar wohi hai jahan ESSANZA ho. Ceramic vase set jo aap ke living room ki shaan bade ga. Minimal design, maximum impact.",
    price: 3990,
    images: ["/images/c8bd98e3-024d-4954-acf8-f7d1ad496230.JPG"],
    colors: [
      { name: "Matte White", hex: "#F5F5F5" },
      { name: "Matte Black", hex: "#2F2F2F" },
    ],
    tags: ["new", "home"],
    rating: 4.6,
    reviewCount: 54,
    inStock: true,
    isNew: true,
    isTrending: false,
    onSale: false,
    createdAt: "2026-05-10",
  },
  {
    id: "prd-042",
    name: "ESSANZA Watch Classic Chronograph",
    slug: slugify("ESSANZA Watch Classic Chronograph"),
    category: "Lifestyle Products",
    subcategory: "Watches",
    description: "Waqt ESSANZA ke saath guzarta hai to accha lagta hai. Classic chronograph watch — stainless steel strap, sapphire glass. Har mard ki pehchaan.",
    price: 15990,
    salePrice: 12990,
    images: ["/images/ca403492-4291-471c-b356-ab6df2875135.JPG"],
    colors: [
      { name: "Silver", hex: "#C0C0C0" },
      { name: "Gold", hex: "#FFD700" },
    ],
    tags: ["sale", "premium"],
    rating: 4.7,
    reviewCount: 43,
    inStock: true,
    isNew: true,
    isTrending: true,
    onSale: true,
    createdAt: "2026-05-11",
  },
  {
    id: "prd-043",
    name: "ESSANZA Sunglasses Aviator",
    slug: slugify("ESSANZA Sunglasses Aviator"),
    category: "Fashion Accessories",
    subcategory: "Sunglasses",
    description: "Dhoop ho ya style, ESSANZA ka aviator sunglasses dono mein kaam aata hai. UV protection ke saath premium look. Jab pehno to lage ke koi film star ho.",
    price: 2990,
    images: ["/images/D-14Closeup_H.jpg", "/images/D-14Closeup_E.jpg"],
    colors: [
      { name: "Black Frame", hex: "#000000" },
      { name: "Gold Frame", hex: "#D4AF37" },
    ],
    tags: ["trending", "summer"],
    rating: 4.5,
    reviewCount: 123,
    inStock: true,
    isNew: false,
    isTrending: true,
    onSale: false,
    createdAt: "2026-04-28",
  },
  {
    id: "prd-044",
    name: "ESSANZA Men Wallet Leather RFID",
    slug: slugify("ESSANZA Men Wallet Leather RFID"),
    category: "Fashion Accessories",
    subcategory: "Wallets",
    description: "Paisa ho ya card, ESSANZA ka wallet mein sab safe hai. Genuine leather with RFID protection. Slim design, smart look.",
    price: 3490,
    images: ["/images/MKDEA2613BlueCloseup_G.webp"],
    colors: [
      { name: "Brown", hex: "#8B4513" },
      { name: "Black", hex: "#000000" },
    ],
    tags: ["bestseller", "gift"],
    rating: 4.7,
    reviewCount: 234,
    inStock: true,
    isNew: false,
    isTrending: false,
    onSale: false,
    createdAt: "2026-03-25",
  },
  {
    id: "prd-045",
    name: "ESSANZA Kids Hair Accessories Set",
    slug: slugify("ESSANZA Kids Hair Accessories Set"),
    category: "Kids Accessories",
    subcategory: "Hair Accessories",
    description: "Choti pariyon ke baal mein ESSANZA ka laga ho to kya baat hai! Hair clips, bands, and bows set — 12 pieces of pure cuteness.",
    price: 990,
    images: ["/images/9900481c-b835-4509-89aa-3da1530c112c.JPG"],
    colors: [
      { name: "Pink Set", hex: "#FF69B4" },
      { name: "Rainbow", hex: "#FF0000" },
    ],
    tags: ["bestseller", "gift"],
    rating: 4.8,
    reviewCount: 345,
    inStock: true,
    isNew: false,
    isTrending: true,
    onSale: false,
    createdAt: "2026-04-22",
  },
];

export const getProductsByCategory = (category: string) =>
  products.filter((p) => p.category === category);

export const getProductsByTag = (tag: string) =>
  products.filter((p) => p.tags.includes(tag));

export const getProductBySlug = (slug: string) =>
  products.find((p) => p.slug === slug);

export const getRelatedProducts = (product: Product, limit = 4) =>
  products.filter(
    (p) => p.category === product.category && p.id !== product.id
  ).slice(0, limit);

export const featuredProducts = products.filter(
  (p) => p.isTrending || p.isNew
).slice(0, 8);

export const saleProducts = products.filter((p) => p.onSale);
