import { Testimonial } from "@/types";

export const testimonials: Testimonial[] = [
  {
    id: "test-001",
    name: "Fatima Ahmed",
    location: "Karachi",
    text: "Maine ESSANZA se pehli baar order kiya toh thoda skeptical thi, but jab parcel aaya tou OMG! Quality itni achi thi ke maine turant do aur suits order kar diye. Khawab 3-piece toh bilkul dream jaisa hai. Fabric bhi super soft hai aur embroidery ek dum premium. Definitely recommend karti hoon!",
    rating: 5,
    avatar: "/images/78e955a7-4a60-4860-baf6-6aa19ad0271d.JPG",
  },
  {
    id: "test-002",
    name: "Mohammad Usman Khan",
    location: "Lahore",
    text: "Mard Stitched kurta shalwar liya tha — ek dum perfect fit aaya. Fabric quality bohot achi hai aur tailoring bhi sahi hai. Pehle mein Stylo aur Junaid Jamshed se leta tha but ab ESSANZA ka ho gaya hoon. Next mein shoes bhi order karunga.",
    rating: 5,
    avatar: "/images/D-14Front_A.jpg",
  },
  {
    id: "test-003",
    name: "Ayesha Tariq",
    location: "Islamabad",
    text: "ESSANZA ka jewelry dekh ke dil kuch karta hai! Maine earrings aur necklace set liya tha wedding season ke liye. Itna elegant hai ke log poochte hain kidhar se liya. Gold plating ka color bhi original laga. Next target — handbags!",
    rating: 5,
    avatar: "/images/JANEA2601PinkRhodolite_C.webp",
  },
  {
    id: "test-004",
    name: "Sana Javed",
    location: "Rawalpindi",
    text: "Bedsheet set bohot zabardast hai! Naram cotton hai aur print bhi stylish hai. 6-piece set itni affordable price mein kahi nahi milta. ESSANZA ka bedding mujhe bohot relax feel karwata hai. Ab pillow covers bhi order kar rahi hoon.",
    rating: 4,
    avatar: "/images/9900481c-b835-4509-89aa-3da1530c112c.JPG",
  },
  {
    id: "test-005",
    name: "Zain Ali",
    location: "Faisalabad",
    text: "Bluetooth speaker liya sale ke time — absolute steal deal thi! Sound quality excellent hai aur battery life bhi 12 hours ka claim hai, 10-11 hours toh aaram se chalta hai. Delivery bhi time par ayi. ESSANZA ne dil jeet liya.",
    rating: 4,
    avatar: "/images/D-14Closeup_E.jpg",
  },
  {
    id: "test-006",
    name: "Maria Sheikh",
    location: "Multan",
    text: "Mujhe makeup products ka shauq hai toh ESSANZA ka kajal aur lipstick try kiya. Kajal toh ek dum zero smudge hai aur lipstick ka matte finish 7-8 hours stay karta hai. Price bhi reasonable hai. Ab glow serum bhi order kar rahi hoon. Best Pakistani brand seriously!",
    rating: 5,
    avatar: "/images/c8bd98e3-024d-4954-acf8-f7d1ad496230.JPG",
  },
  {
    id: "test-007",
    name: "Ahmed Raza",
    location: "Gujranwala",
    text: "Formal loafers liye job interview ke liye. Pehne toh bilkul perfect fit tha aur leather quality bhi achi hai. Interview bhi clear ho gaya so maybe ESSANZA lucky hai! Ab casual sneakers ka order soch raha hoon. Highly recommended for men who care about style.",
    rating: 5,
    avatar: "/images/D-14Closeup_H.jpg",
  },
  {
    id: "test-008",
    name: "Bisma Khalid",
    location: "Peshawar",
    text: "Bachon ke frock bohat cute aaye! Fabric soft hai aur stitching neat hai. ESSANZA ka kids collection bohot zabardast hai. Mera beta sneakers bohot enjoy kar raha hai. Next time poori family ka order karungi.",
    rating: 5,
    avatar: "/images/ca403492-4291-471c-b356-ab6df2875135.JPG",
  },
  {
    id: "test-009",
    name: "Rubaisha Imran",
    location: "Sialkot",
    text: "ESSANZA ka handbag — OMG! Bohot stylish hai aur size bhi perfect hai. Itna sara samaan aata hai us mein. Tan colour toh har outfit ke saath jaata hai. Friends ne bhi bohot appreciate kiya. ESSANZA rocks!",
    rating: 5,
    avatar: "/images/mkd-ef21-23-blueb_4c223133-92d3-4ee2-9934-d20710246362.webp",
  },
  {
    id: "test-010",
    name: "Hassan Ali",
    location: "Hyderabad",
    text: "Walet tha rfid protection k sath or bilkul lether feel ha. Paisa b zyada nai laga or quality bohat achi ha. ESSANZA k sath abhi tk kafi products liye hn or koi complain nai ha. Keep it up ESSANZA team!",
    rating: 4,
    avatar: "/images/MKDEA2613BlueCloseup_G.webp",
  },
];
